### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by cleesmith** [jasonish/go-unified2#1]
For the day job, we are using py-idstools within a tool like uni2espy. That has worked great...thanks.
Recently I noticed that Elastic started adding open source collectors they call [Beats](https://www.elastic.co/guide/en/beats/libbeat/current/new-beat.html). 

Then I noticed go-unified2 and thought this may be a good starting point to create a new beat ... IntruderBeat or whatever. It seems the go-unified2 repo isn't as complete as the py-idstools. While there is an aggregator, there isn't a **SpoolEventReader** for a directory of unified2 files ... with follow and bookmarks. I am guessing this repo doesn't get much use, or are there a technical reasons hindering any enhancements?

I am thinking this may be a good side project. 
Of course, you are in a better position to code it than I am given your familiarity with unified2. 
Thoughts?

**Comment by jasonish** [comment]
I did this in Go when I was doing more in Go, but haven't done much with Go lately, however I've been getting back into it and may have a real need for this - actually I will have a real need for this.

However, I'm not keen on keeping any sort of aggregator based code in here.  To do ordering of records in a unified2 record stream, I'm not happy with the results you can end up with and have decided that its best for the application to to its own grouping of records rather than trying to make a generic solution.

For example, if an event has tagged events you might get something like this..

- Event 1
- Packet for event 1
- Event 2
- Packet for event 2
- Packet for event 1
- Event 3
- Packet for event 3
- Packet for event 1
- Event 4
- Packet for event 4
- Event 5
- Packet for event 5
- Packet for event 1

Different applications will want to deal with this differently, and I'd rather not have the library take care of it.  So I'll probably trim this unified2 lib down to the core record reading, and perhaps some bookmarking, but the EventReader will likely go.

**Comment by cleesmith** [comment]
I didn't realize that about the unified2 record stream.
Is this somehow handled differently in py-idstools, which does seem to have an aggregator?
Or is it this issue:
https://github.com/jasonish/py-idstools/issues/14
All of this makes it sound almost impossible to reliably index unified2 files into elasticsearch.

**Comment by jasonish** [comment]
py-idstools has the same issue.  As each record contains the event-id that it is associated with, the aggregator will only aggregate records that have the same event-id as the last event record seen.  If it sees a packet record for an event that is not the most recently, it will be tossed out as the aggregate has already flushed out that event - so what do we do with it??

This works fine for my use case of making Suricata compatible eve-logs where we only want one packet per event record anyways, so I'm happy throwing any others out.

Barnyard2 does not have to deal with this as I believe it stores each unified2 record in the database independently.  So the event record is added to an event table, and the packet record is added to the packet table.  So if a packet record is seen for some prior event, it can just add it to the right table, and JOIN's can be used to find all event records for a given event.

With ElasticSearch where you most likely want all the packets embedded in the event document that is going to be a little harder to do.  Perhaps partial doc updates? This is why I think its best left up to the application, rather than the library to figure things out.

**Comment by jasonish** [comment]
I'll probably keep the aggregator as is in py-idstools, as I think it does serve some utility.  But I'll probably remove it from go-unified2.

**Comment by cleesmith** [comment]
It has been a while since we used Barnyard2, so I had forgotten about all of those db tables with join ... we've been spoiled by ElasticSearch(ES). I guess updates are possible for ES, just slow and wasteful with Lucene indices (or they used to be?). 

Perhaps just indexing with different ```_type```s for the different types of records comprising an event would work. After all, for our usage, most of the searches performed are in the fields within the EventRecord (src/dst ip/port, signature) and the data within the PacketRecord (payload). Then just link the docs based on the EventId. A complication may be if EventId isn't truly unique over a given period of time ... we keep the most recent 2 weeks worth of snort/suricata data for searching. 

Also, I think ES suggests a few ways to deal with [document relationships](https://www.elastic.co/guide/en/elasticsearch/guide/current/relations.html).

Both syslogs and snort/suricata data are unique use cases for ES since the data should never be updated ... compliance and all of that stuff.

It's definitely a plus that the library is generic enough for apps to do as they wish or need.
So I will use the go-unified2 lib without depending on the aggregator.
Thanks for all of the info and this lib ... there's still a lot to try and figure out.

**Comment by jasonish** [comment]
I think you've helped firm up my argument that the aggregation should usually be left up to the application.  Yeah, so as you plan, don't rely on it in this lib.  

I'll be removing it, plus adding support for the newer unified2 event type with app-id support.  Probably in the next week or 2.
